/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from 'bn.js';
import Contract, { contractOptions } from 'web3/eth/contract';
import { EventLog, Callback, EventEmitter } from 'web3/types';
import { TransactionObject, BlockType } from 'web3/eth/types';
import { ContractEvent } from './types';

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class SMT256 extends Contract {
  constructor(jsonInterface: any[], address?: string, options?: contractOptions);
  clone(): SMT256;
  methods: {
    EXIST(): TransactionObject<string>;

    NON_EXIST(): TransactionObject<string>;
  };
  events: {
    allEvents: (options?: EventOptions, cb?: Callback<EventLog>) => EventEmitter;
  };
}
